version: '3'
services:
  db:
    image: postgres
    volumes:
      - ../api/sql:/docker-entrypoint-initdb.d/
  wait:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432 api:3000
  api:
    image: caires/store-api:v1.0.0
    environment:
      - NODE_ENV=production
      - PG_USER=postgres
      - PG_HOST=db
      - PG_DB=postgres
      - PG_PORT=5432
      - API_NAME=mmartan-api
      - API_VERSION=stage
    ports:
      - "3001:3000"
  render:
    image: caires/store-render:v1.0.0
    ports:
      - "2345:1234"
    depends_on:
      - wait
