version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
  wait:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432
  api:
    image: caires/mmartan:v1.0.0
    environment:
      - PG_USER=postgres
      - PG_HOST=db
      - PG_DB=postgres
      - PG_PORT=5432
      - API_NAME=mmartan-api
      - API_VERSION=stage
    ports:
      - "3001:3000"
    depends_on:
      - wait